language: node_js
sudo: false

script: "/bin/date"

node_js:
  - 0.12

install: 
  - npm install
  - npm install -g gulp

services: mongodb

script:
  - cp config.json.travis config.json
  - gulp
  - gulp test
  - npm start

before_deploy:
  - gem install mime-types -v 2.6.2


deploy:
  - provider: s3
    access_key_id:
      secure: RSbJV8MZaIxbpJA0yT/qp+7nBPzQmjkzPErb8t4ZpAkebsTVKAd7/e//fXFJguSUoPx57zGRxCJNTvuF7uZSZ4Vl85JZXInzQnKI5nFP8FfqqSZmH6mYf6+m0MFHVYy4s0SX5/IGkMCRIFoKK3PJ7HnizrYdmTOywcSxrsSI8F0=
    secret_access_key:
      secure: bxuBwOeamiW+xysEbyJ1r1KhcHg5WtJUqDv8tIpw1t06D6AeJ0frny64bPWYq9DiOYJetqifUq9ppRdafVP4JbR5rbn9ryXkvR+NeySZ0tQZask9udwsxK8bz/YC00511TTYt7l3x24neIWqQJ3HNMJSU4bXMusdlK/wGYymn/o=
    bucket: wrioos.com
    upload-dir: Core-WRIO-App
    acl: public_read
    on:
      branch: production
  - provider: opsworks
    access_key_id:
      secure: rV/Q5DTtUntw6fGacEnliXXM3f8X2OqAVibEQv5iSo/9ND1wt9dIOyzs5bvwPy4477a8pzVB/b3b9lDmSJir4fLyHXtOcfrfi4k2CXVlhYqwY5g1GyLFf07mfZM3ZqR3qZZb7D/MbQwdOQyA0EgglGGdYhu0zs0Cd8TEaoScPQg=
    secret_access_key:
      secure: K7gZSEIrNpySChU15C5LIgzxLnCylOMXPwHJIj4YxW0dX9pHbT4CfNNywoIhzvbngpkvfnrCSFmmxw2s/KUpgV1LWnN9RqDBLvec/cBlEsFgS+t+8X+NB1PYdVITGIFrhXmU766F4DUItUyOdRtdti3OHIp92BPLiH/CWfqDby8=
    app-id: d2c52b21-65f4-4079-9f4e-6474046f7d97
    on:
      branch: production
